sudo: required
language: cpp

matrix:
  include:
    - os: linux
      env:
        - CC=gcc-9
        - CXX=g++-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake

    - os: linux
      dist: xenial
      env:
        - CC=clang-8
        - CXX=clang++-8
        - CXXFLAGS="-stdlib=libc++"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - cmake

    - os: osx
      osx_image: xcode11.2
      env:
        - CC=clang
        - CXX=clang++

script:
  - cmake -DCMAKE_BUILD_TYPE=Release . && make
  - ./alignment_tests && ./minimizers_tests
